leftnav:
- identifier: fa7ecf4f-0c2c-9097-dfd9-9130025d2a5e
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: b29cbcda-d374-8545-0b13-c936975b3378
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 0eb5f92e-fc86-94fa-0f99-aa1e2380b2df
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 928c437f-4c3e-3960-c760-cc5f4a6fce94
  name: Assignments
  url: /pages/assignments
  weight: 40
